### ISSUE TITLE
MysqlActivityStoreSpec falis

### ISSUE THREAD

**Issue by david-guzman** [pddisense/pdd-server#1]
When running ./sbt compile test I get the following error message

```
[info] MysqlActivityStoreSpec:
[info] ucl.pdd.storage.mysql.MysqlActivityStoreSpec *** ABORTED ***
[info]   com.twitter.finagle.Failure: Connection refused: /0.0.0.0:3306 at remote address: /0.0.0.0:3306. Remote Info: Not Available
[info]   ...
[info]   Cause: com.twitter.finagle.ConnectionFailedException: Connection refused: /0.0.0.0:3306 at remote address: /0.0.0.0:3306. Remote Info: Not Available
[info]   at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:100)
[info]   at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:79)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
[info]   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[info]   at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
[info]   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
[info]   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
[info]   ...
[info]   Cause: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:3306
[info]   at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[info]   at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
[info]   at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
[info]   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
[info]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
[info]   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   ...
[info]   Cause: java.net.ConnectException: Connection refused
[info]   at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[info]   at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
[info]   at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
[info]   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
[info]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
[info]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
[info]   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   ...
```

Using Java 1.8 on Mac
```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

**Comment by pvcnt** [comment]
You need a local MySQL server running in order to successfully launch all the tests. I will update the README accordingly.

Please run `./sbt compile` to only build the server, or `./sbt run` to start it locally.

**Comment by david-guzman** [comment]
I can look into using an embedded instance of MySQL for running tests

https://github.com/wix/wix-embedded-mysql could be an option
